### ISSUE TITLE
Exiting due to error in template.

### ISSUE THREAD

**Issue by cmhh** [playframework/play-scala-seed.g8#74]
This was working for me yesterday, but not now.  I see there was an edit 15 hours ago.  For me it bails out after I try entering the organisation name:

```bash
cmhh@cmhh-laptop:~/projects$ sbt new playframework/play-scala-seed.g8
[info] Loading global plugins from /home/cmhh/.sbt/1.0/plugins
[info] Set current project to projects (in build file:/home/cmhh/projects/)
[info] Set current project to projects (in build file:/home/cmhh/projects/)

This template generates a Play Scala project 

name [play-scala-seed]: test
organization [com.example]: 

Exiting due to error in the template: /tmp/giter8-561573547906450
File: /tmp/giter8-561573547906450/src/main/g8/build.gradle, 59:71: mismatched input '.' expecting LPAREN
```

The line in question is:

```as.is
    playTest "org.scalatestplus.play:scalatestplus-play_$scalaVersion:3.1.2"
```

which I think should be?:

```as.is
    playTest "org.scalatestplus.play:scalatestplus-play_\$scalaVersion:3.1.2"
```

Cheers

**Comment by pietervanlill** [comment]
Having the same issue. How can we bypass this until they have fixed it?

Edit:

Clone the repo. Escape the `$` then use `sbt new file://play-scala-seed.g8/`

#75 Should fix the issue

**Comment by mikail-khan** [comment]
This is STILL happening.

Exiting due to error in the template: /tmp/giter8-181685144086758
File: /tmp/giter8-181685144086758/src/main/g8/build.gradle, 59:71: mismatched input '.' expecting LPAREN

**Comment by tdgs** [comment]
This commit seems to have explicitly removed the escape: https://github.com/playframework/play-scala-seed.g8/commit/b28045aece55f3993a0f9e2b78aece7ca61804c9#diff-2b2b73e47e4083fd40c15ae3964baf1fL59
